baseurl = "/"
languageCode = "en-nz"
languageLang = "en"
title = "Lorna Jacob"
author = "Lorna Jacob"
theme = "terrassa"
defaultContentLanguage = "en"

[params.hero]
	textColor = "#db7093"

[params.posts]
    showAuthor = true
    showDate = true
    showTags = true
    dateFormat = "Monday, Jan, 2006"

[params.form] # Contact form
    netlify = true
    action = "https://formspree.io/lornzjacob@gmail.com"
    method = "POST"
    inputNameName = "name"
    inputNameLabel = "Name"
    inputNamePlaceholder = "Your name"
    inputEmailName = "email"
    inputEmailLabel = "Email"
    inputEmailPlaceholder = "Your email"
    inputMsgName = "message"
    inputMsgLabel = "Your message"
    inputMsgLength = 750
    inputSubmitValue = "Send"

[languages]
	[languages.en]
		languageName = "en"
		weight = 1
		contentDir = "content/en"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
